In [77]:
import numpy as np

In [6]:
array1=np.arange(1,10).reshape(3,3)
array2=np.arange(1,10).reshape(3,3)
print(array1)
print("    +")
print(array2)
print()
add_array=array1 + array2 

print("Addition of two arrays \n", add_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
    +
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Addition of two arrays 
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


# BY functions:

# Add sub mul divide

In [7]:
array1=np.arange(1,10).reshape(3,3)
array2=np.arange(1,10).reshape(3,3)

add=np.add(array1 , array2)
print(f"Addition of two array is : \n{add}")

print( )
sub=np.subtract(array1 , array2)
print(f"SUbtraction of two array is : \n{sub}")

print( )
mul=np.multiply(array1,array2)
print(f"Multiplication of two array is : \n{mul}")

print( )
divide=np.divide(array1 , array2)
print(f"Division of two array is : \n{divide}")



Addition of two array is : 
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

SUbtraction of two array is : 
[[0 0 0]
 [0 0 0]
 [0 0 0]]

Multiplication of two array is : 
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]

Division of two array is : 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


# Matrix multiplication

# simple operators

In [8]:
matrix=array1 @ array2
print(matrix)

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


# By function

In [9]:
matrix=np.dot(array1,array2)
print(matrix)

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


# Max and min value

In [10]:
matrix1=np.max(array1)
matrix2=np.min(array2)                 # max values
print(f"Max values array1 : {matrix1}\nMin value of array1: {matrix1}") # min values
print()
print(f"Max values array2 : {matrix2}\nMin value of array2: {matrix2}") 


Max values array1 : 9
Min value of array1: 9

Max values array2 : 1
Min value of array2: 1


# Index of max value(argmax/argmin)

In [11]:
matrix1=np.argmax(array1)
matrix2=np.argmin(array2)                 # max values
print(f"Max values array1 : {matrix1}\nMin value of array1: {matrix1}") # min values
print()
print(f"Max values array2 : {matrix2}\nMin value of array2: {matrix2}") 


Max values array1 : 8
Min value of array1: 8

Max values array2 : 0
Min value of array2: 0


# Using Axis
 x-axis(rows - vstack) = 1
 
 y-axis(coloumns - hstack) = 0

In [12]:
arra1=np.array([[1,6,7,4],[5,6,8,4]])
print(arra1)


print()

# min & max  value at coloumns
min_ax=arra1.min(axis=1)
print("Min values in rows:" , min_ax)

print()

max_ax=arra1.max(axis=1)
print("Max values in coloumns:" , max_ax)

[[1 6 7 4]
 [5 6 8 4]]

Min values in rows: [1 4]

Max values in coloumns: [7 8]


# Adding values...by rows and coloumns(min and max)

In [13]:
arra1=np.array([[1,6,7,4],[5,6,8,4]])
print(arra1)


add_min=np.sum(arra1)
print(add_min)

[[1 6 7 4]
 [5 6 8 4]]
41


In [14]:
add_with_axis=np.sum(arra1,axis=0)
print(add_with_axis)  # answer coloums wise


[ 6 12 15  8]


In [15]:
add_with_axis=np.sum(arra1,axis=1) # anwer rows
print(add_with_axis)


[18 23]


In [16]:
add_with_axis.mean()

20.5

In [4]:
import numpy as np
a=np.array([3,4,5,6,6])
b=np.array([4,5,5,6,7])


In [7]:
square=np.square(a)
print(square)

[ 9 16 25 36 36]


In [30]:
square_root=np.sqrt(b)
print(square_root)

[2.         2.23606798 2.23606798 2.44948974 2.64575131]


In [12]:
log=np.log(a)
print(log)

[1.09861229 1.38629436 1.60943791 1.79175947 1.79175947]


In [14]:
log10=np.log10(b)
print(log10)

[0.60205999 0.69897    0.69897    0.77815125 0.84509804]


In [29]:
sin=np.sin(a)
cos=np.cos(b)
tan=np.tan(a)
print("Sin : " ,sin)
print("COs : " ,cos)
print("Tan : " ,tan)

Sin :  [ 0.14112001 -0.7568025  -0.95892427 -0.2794155  -0.2794155 ]
COs :  [-0.65364362  0.28366219  0.28366219  0.96017029  0.75390225]
Tan :  [-0.14254654  1.15782128 -3.38051501 -0.29100619 -0.29100619]


In [ ]:
# Numpy calcultor

##### 