# Concatenate 
it is use to join one or more than array

syntax:

np.concatenate( (shape1,shape2) )   alwys pass tuples

In [2]:
import numpy as np

In [4]:
shape1=np.arange(1,17).reshape(4,4)
print(shape1)
print()
shape2=np.arange(17,33).reshape(4,4)
print(shape2)



[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

[[17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [25]:
con=np.concatenate((shape1,shape2))
print(con)
print(con.ndim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]
2


In [24]:
arr=shape1 + shape2
print(arr)   # it will be add  not be concatenate

[[18 20 22 24]
 [26 28 30 32]
 [34 36 38 40]
 [42 44 46 48]]


In [13]:
shape2=np.arange(17,33).reshape(4,4)
print(shape2)

[[17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [16]:
list1=[3,4,56,6]
list2=[5,7,78,7]
equal=list1 + list2    # list can be concatenate but matrix can not...
print(equal)

[3, 4, 56, 6, 5, 7, 78, 7]


# Rows and coloumns wise concatenate
by default row = 1

           coloumns = 0

In [9]:

arr1=np.arange(1,11).reshape(2,5)
arr2=np.arange(11,21).reshape(2,5)


# horizontal means coloums wise....
arr=np.concatenate((arr1,arr2),axis=1)
print(arr)



print()


#vertical means rows wise
arr=np.concatenate((arr1,arr2),axis=0)
print(arr)





[[ 1  2  3  4  5 11 12 13 14 15]
 [ 6  7  8  9 10 16 17 18 19 20]]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


# by hstack nd vstack

hstack=horizontal wise(axis=1)

vstack=vertical wise  (axis=0)

In [68]:
arr_hs=np.hstack((arr1,arr2))
print(arr_hs)


[[11 12 13 14 15 11 12 13 14 15]
 [16 17 18 19 20 16 17 18 19 20]]


In [69]:
arr_vs=np.vstack((arr1,arr2))
print(arr_vs)


[[11 12 13 14 15]
 [16 17 18 19 20]
 [11 12 13 14 15]
 [16 17 18 19 20]]


# Split Fuction
Its is use to split array

split functions retruns list

In [75]:
arr1=np.arange(1,11).reshape(2,5)
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [84]:
split_array=np.split(arr1,2)
print(split_array)
print(type(split_array))

[array([[1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10]])]
<class 'list'>


In [90]:
split_array[0]
# type(split_array)

array([[1, 2, 3, 4, 5]])

In [91]:
split_array[0:]
# type(split_array)

[array([[1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10]])]

In [92]:
split_array[1]

array([[ 6,  7,  8,  9, 10]])

In [119]:
# Example of concatenate and split......Row wise......
a1=np.arange(1,21).reshape(2,10)
a2=np.arange(1,11).reshape(2,5)

print("first array :\n"  ,a1)
print()
print( "secound array :\n" , a2)

print("\n")
print("Concatenate array 1 and array 2 : \n")
a=np.concatenate((a1,a2),axis=1)
print(a)

print("\n")
print("split array into 2 peices")

s=np.split(a,2)
for i in s :
    print(i)


first array :
 [[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]

secound array :
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


Concatenate array 1 and array 2 : 

[[ 1  2  3  4  5  6  7  8  9 10  1  2  3  4  5]
 [11 12 13 14 15 16 17 18 19 20  6  7  8  9 10]]


split array into 2 peices
[[ 1  2  3  4  5  6  7  8  9 10  1  2  3  4  5]]
[[11 12 13 14 15 16 17 18 19 20  6  7  8  9 10]]


In [11]:
# Example of concatenate and split......coloumns wise......
a1=np.arange(1,21).reshape(10,2)
a2=np.arange(1,11).reshape(5,2)

print("first array :\n"  ,a1)
print()
print( "secound array :\n" , a2)

print("\n")
print("Concatenate array 1 and array 2 : \n")
a=np.concatenate((a1,a2),axis=0)
print(a)

print("\n")
print("split array into 3 peices")

s=np.split(a,3)
# for i in s :
#     print(i,"\n")
s


first array :
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]]

secound array :
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


Concatenate array 1 and array 2 : 

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]
 [ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


split array into 3 peices


[array([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]]), array([[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]]), array([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]])]

# Split with 1D array

In [135]:
arra1=np.array([3,5,6,7])
sp=np.split(arra1, [1,3])
print(sp)

[array([3]), array([5, 6]), array([7])]


In [140]:
arr1=np.array([4,78,56,4,5,6,8,8,7,6,5,2,67,8,65,4])
split=np.split(arr1,[3,8,11])  # index of an elements
print(split)

[array([ 4, 78, 56]), array([4, 5, 6, 8, 8]), array([7, 6, 5]), array([ 2, 67,  8, 65,  4])]
