# Numpy:
its is the library of python is perform data according to 1d and 2d array

In [8]:
import numpy as np    #cltr+Enter= only  and  shift+ENter=execute and create a new cell..

# 1D Array

In [11]:
# np is  a key word and array is a constant....

one_d_array=np.array([1,2,3,4])
print(one_d_array)
print(type(one_d_array))

[1 2 3 4]
<class 'numpy.ndarray'>


# find dimension and size of Array

In [26]:
# name.ndim  (name of dimension)
print(one_d_array.ndim)   #one dimension array
print(one_d_array.size)



1
4


# 2D Array

In [39]:
print("With for loop")
_2D_array=np.array([[1,2,3,4,5,6],[1,3,6,7,8,76]])
for i in _2D_array:
    print(i)
print("\n")
print("Without for loop")
print(_2D_array)

#dimension  and size of array

print(f"\nDimension of Array is : {_2D_array.ndim}D")
print(f"\nSize of Array is : {_2D_array.size}")

With for loop
[1 2 3 4 5 6]
[ 1  3  6  7  8 76]


Without for loop
[[ 1  2  3  4  5  6]
 [ 1  3  6  7  8 76]]

Dimension of Array is : 2D

Size of Array is : 12


In [35]:
# names=['sadiq shah','Ali',"Kashif"]
# ages=[12,45,65]
# _2d_array=np.array([[names,ages]])
# print(_2d_array)

[[['sadiq shah' 'Ali' 'Kashif']
  ['12' '45' '65']]]


# shapes of an Array
how many rows

how many coloumns

In [46]:
# 1st list=row
# 2nd list=coloumn
# _2d_array=np.array([[1,2,3],[1,2,3]])
_2D_array.shape 
# (2,6)   here 2 is the number of rows and 6 is the number of coloumns 

(2, 6)

# check data type

In [51]:
print(f"The data type of the 2D array is : {_2D_array.dtype}")

The data type of the 2D array is : int32
