# Fancy Indexing

In [15]:
import numpy as np
arra1=np.arange(10)
print(arra1)

arra1[[1,8,4]]



[0 1 2 3 4 5 6 7 8 9]


array([1, 8, 4])

In [23]:
_3D=np.arange(30).reshape(5,6)
print(_3D)
f_i=_3D[[2,0,4]]
print("\n")
print(f_i)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


[[12 13 14 15 16 17]
 [ 0  1  2  3  4  5]
 [24 25 26 27 28 29]]


In [24]:
_3D=np.arange(30).reshape(5,6)
print(_3D)
f_i=_3D[[0,1,2]]
print("\n")
print(f_i)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]


In [25]:
_3D=np.arange(30).reshape(5,6)
print(_3D)
f_i=_3D[[-2,0,-4]]
print("\n")
print(f_i)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


[[18 19 20 21 22 23]
 [ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
