# Range: in numpy Arange

In [1]:
import numpy as np

In [4]:
#create a array to print counting 1 to 100

counting=np.arange(1,100)
print(counting)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]


In [5]:
# create an array to print 10 squares...
squares=np.arange(1,100)
a=squares**2
print(a)



[   1    4    9   16   25   36   49   64   81  100  121  144  169  196
  225  256  289  324  361  400  441  484  529  576  625  676  729  784
  841  900  961 1024 1089 1156 1225 1296 1369 1444 1521 1600 1681 1764
 1849 1936 2025 2116 2209 2304 2401 2500 2601 2704 2809 2916 3025 3136
 3249 3364 3481 3600 3721 3844 3969 4096 4225 4356 4489 4624 4761 4900
 5041 5184 5329 5476 5625 5776 5929 6084 6241 6400 6561 6724 6889 7056
 7225 7396 7569 7744 7921 8100 8281 8464 8649 8836 9025 9216 9409 9604
 9801]


In [6]:
reverse_counting=np.arange(100,1,-1)
print(reverse_counting)

[100  99  98  97  96  95  94  93  92  91  90  89  88  87  86  85  84  83
  82  81  80  79  78  77  76  75  74  73  72  71  70  69  68  67  66  65
  64  63  62  61  60  59  58  57  56  55  54  53  52  51  50  49  48  47
  46  45  44  43  42  41  40  39  38  37  36  35  34  33  32  31  30  29
  28  27  26  25  24  23  22  21  20  19  18  17  16  15  14  13  12  11
  10   9   8   7   6   5   4   3   2]


In [7]:
even_no=np.arange(0,10,2)
print(even_no)

[0 2 4 6 8]


In [8]:
odd_no=np.arange(1,10,2)
print(odd_no)

[1 3 5 7 9]


In [12]:

print("======================================")
print("Table:your range,your table selection by using arange function")
print("======================================")
ran_start=int(input("Enter a start range of the table : "))
ran_End=int(input("Enter a end range of the table : "))
ran_table=int(input("Enter a number of the table : "))
rangee=np.arange(ran_start,ran_End+1)
table=rangee*ran_table
for i in table:
    print(i,end="   ")









Table:your range,your table selection by using arange function
Enter a start range of the table : 1
Enter a end range of the table : 50
Enter a number of the table : 10
10   20   30   40   50   60   70   80   90   100   110   120   130   140   150   160   170   180   190   200   210   220   230   240   250   260   270   280   290   300   310   320   330   340   350   360   370   380   390   400   410   420   430   440   450   460   470   480   490   500   

# linspace
A nmber break down into other parts

In [ ]:
ran_start=int(input("Enter a start range of the number : "))
ran_End=int(input("Enter a end range of the number : "))
n_p=int(input("How many piceces do you want to entered Ending number : "))
a=np.linspace(ran_start,ran_End,n_p)
print(a)


In [ ]:
a=np.linspace(2,10,10)
print(a)

# Reshape

In [ ]:
_1d_array=np.array([1,2,3,4,5,6])
print(_1d_array)

print(_1d_array.ndim)
_2d_array=_1d_array.reshape((2,3))
print(_2d_array)
print(_2d_array.ndim)


In [ ]:
a=np.array([[1,2,3],[1,5,7]])
print(a)
print(a.ndim)
b=a.reshape(6)
print(b)
print(b.ndim)


c=a.reshape(1,3,2)
print(c)
print(c.ndim)


In [ ]:
ar=np.array([[[1,3,5],[1,3,5]] , [[1,3,5],[1,3,5]] , [[1,3,5],[1,3,5]]])
print(ar.shape)
print(ar.size)
print(ar.ndim)
a=ar.reshape(18,)
print(a.ndim)


b=ar.reshape(3,6)
print(b)
print(b.shape)
print(b.size)
print(b.ndim)



c=ar.reshape(2,9)
print(c)
print(c.shape)
print(c.size)






In [ ]:
D=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[15,16,17]],[[18,19,20],[21,22,23],[24,25,26]]])
D[1,1,0:2]

In [14]:
print('=====================')
print("Creating Dimensions")

print('=====================')
print("1 Dimensions")
print("=====================\n")
_3D_array=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[15,16,17]],[[18,19,20],[21,22,23],[24,25,26]]])
print(f"3D array is  :\n{_3D_array}\n")
print(f"Dimension of 3D : {_3D_array.ndim}\n")
print(f"Size of an 3D array : {_3D_array.size}\n")


print('=====================')
print("2 - Dimensions")
print("=====================\n")
_2D_array=_3D_array.reshape(3,9)
print(f"2D array is  :\n{_2D_array}\n")
print(f"Dimension of 2D : {_2D_array.ndim}\n")
print(f"Size of an 2D array : {_2D_array.size}\n")





print('=====================')
print("3 - Dimensions")
print("=====================\n")
_1D_array=_2D_array.reshape(27,)
print(f"1D array is  :\n{_1D_array}\n")
print(f"Dimension of 1D : {_1D_array.ndim}\n")
print(f"Size of an 1D array : {_1D_array.size}\n")

Creating Dimensions
1 Dimensions

3D array is  :
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]

Dimension of 3D : 3

Size of an 3D array : 27

2 - Dimensions

2D array is  :
[[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 15 16 17]
 [18 19 20 21 22 23 24 25 26]]

Dimension of 2D : 2

Size of an 2D array : 27

3 - Dimensions

1D array is  :
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 15 16 17 18 19 20 21 22 23
 24 25 26]

Dimension of 1D : 1

Size of an 1D array : 27



In [ ]:
import numpy as np
print("You can Created desireable matrix")
print("==================================\n")
start_range=int(input("Enter a no of rows : "))
End_range=int(input("Enter a no of coloumns : "))
no=int(input("Enter a number ,Would you like to create a matrix : "))
a=np.ones((start_range,End_range))*no
print(a)

# Ravel
multi dimestion into one dimension

In [11]:
D=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[15,16,17]],[[18,19,20],[21,22,23],[24,25,26]]])
print(D.ndim)
print(D)
a=D.ravel()
print(a)
print(a.ndim)


3
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 15 16 17 18 19 20 21 22 23
 24 25 26]
1


In [18]:
list1=np.array([[3,4,6],[3,4,5]])
print(list1)
rav=list1.ravel()
print(rav)
rav[0]=100
print(rav)
print(list1)



[[3 4 6]
 [3 4 5]]
[3 4 6 3 4 5]
[100   4   6   3   4   5]
[[100   4   6]
 [  3   4   5]]


In [24]:
list1=np.array([[3,4,6],[3,4,5]])
flat=list1.flatten()
print(flat)

flat[0]=1000
print(flat)

print(list1)

[3 4 6 3 4 5]
[1000    4    6    3    4    5]
[[3 4 6]
 [3 4 5]]


In [3]:
print("Major diffrence b/w ravel and flatten\n")

print("---------------  Ravel -----------")  #its convert multidimentional array into one dimentional.
_2D_arry=np.array([[1,4,5,6] , [2,6,8,8]])
print(f"Original array :\n{_2D_arry}\n")
_1D_arry=_2D_arry.ravel()
print(f"After Ravel : { _1D_arry }")

print("------------  After Change the indexing value -------------------")
_1D_arry[0]=5
print(f"After change the value of Ravel index : { _1D_arry }")
print("------------------Original 2D array before ravel--------------------------")
print(_2D_arry)
print("Note : change the original value with change the vlaue of ravel indexing....")



Major diffrence b/w ravel and flatten

---------------  Ravel -----------
Original array :
[[1 4 5 6]
 [2 6 8 8]]

After Ravel : [1 4 5 6 2 6 8 8]
------------  After Change the indexing value -------------------
After change the value of Ravel index : [5 4 5 6 2 6 8 8]
------------------Original 2D array before ravel--------------------------
[[5 4 5 6]
 [2 6 8 8]]
Note : change the original value with change the vlaue of ravel indexing....


In [2]:
_2D_arry=np.array([[1,4,5,6] , [2,6,8,8]])

print("--------------- Flatten -----------")  #its convert multidimentional array into one dimentional.
print(f"Original array :\n{_2D_arry}\n")
_1D_arry=_2D_arry.flatten()
print(f"After Flatten : { _1D_arry }")

print("------------  After Change the indexing value -------------------")
_1D_arry[0]=5
print(f"After change the value of flatten index : { _1D_arry }")
print("------------------ Original 2D array before flatten --------------------------")
print(_2D_arry)
print("Note : No change the original value with change the vlaue of ravel indexing....")

--------------- Flatten -----------
Original array :
[[1 4 5 6]
 [2 6 8 8]]

After Flatten : [1 4 5 6 2 6 8 8]
------------  After Change the indexing value -------------------
After change the value of flatten index : [5 4 5 6 2 6 8 8]
------------------ Original 2D array before flatten --------------------------
[[1 4 5 6]
 [2 6 8 8]]
Note : No change the original value with change the vlaue of ravel indexing....


# Transpose

In [4]:
_2D_arry=np.array([[1,4,5,6] , [2,6,8,8]])
print(_2D_arry)

a=_2D_arry.T
print(a)



print()
b=_2D_arry.transpose
print(a)

[[1 4 5 6]
 [2 6 8 8]]
[[1 2]
 [4 6]
 [5 8]
 [6 8]]

[[1 2]
 [4 6]
 [5 8]
 [6 8]]


In [18]:
arra1=np.arange(20)
_1D=arra1.reshape(2,10)
print(_1D)


[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


In [38]:
arra1=np.ones((20,20))
# _1D=arra1.reshape(400)   #size is 400
# print(_1D)

# print(_1D.ndim)



_1D=arra1.reshape(2,2,100)   #size is 400
print(_1D)

print(_1D.ndim)


[[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
   1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
   1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
   1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
   1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
   1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
   1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
   1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
   1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
   1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
   1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
   1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
   1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.

In [42]:
# arra2=np.ones((20,20))
# _3D=arra1.reshape(2,2,100)  #size is 400
# print(_3D)
# print(_3D.ndim)



arra22=np.ones((20,20))
_2D=arra1.reshape(10,2,20)  #size is 400
print(_2D)
print(_2D.ndim)




[[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.

In [31]:
a = [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]]

SyntaxError: invalid syntax (<ipython-input-31-6c47ca0e2927>, line 1)