# Matrix

In [3]:
import numpy as np
name=np.array([2,5,6])
print(name)
print(name.shape)  # check the shape of array (how many rows and coloumn-->(n,n) first n is rows and second n is coloumns)
print(name.size)   #Check the size of array(how many  elements contains in array)
print(name.dtype)  #check the data type of the array
print(name.ndim)  # check the dimension of the array (1D or 2D)


[2 5 6]
(3,)
3
int32
1


# Ones Zeros

In [4]:
import numpy as np
ones=np.ones((4,4))
print(ones)
print(ones.ndim)
print(ones.shape)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
2
(4, 4)


In [5]:
zeros=np.zeros((4,4))
ones=np.ones((4,4))
print(ones*zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
print("multiply of two matrix")
a=np.array([[2,3,4],[45,6,7]])
b=np.array([[2,4,4],[4,6,7]])
print(f"Two Matrix multiplied : \n{a*b}")

print('\n')
print("Addition of two matrix")
a=np.array([[2,3,4],[45,6,7]])
b=np.array([[2,4,4],[4,6,7]])
print(f"Two Matrix Added : \n{a + b}")


print('\n')
print("Subtraction of two matrix")
a=np.array([[2,3,4],[45,6,7]])
b=np.array([[2,4,4],[4,6,7]])
print(f"Two Matrix Subtracted : \n{a - b}")


print('\n')
print("Division of two matrix")
a=np.array([[2,3,4],[45,6,7]])
b=np.array([[2,4,4],[4,6,7]])
print(f"Two Matrix Divided : \n{a / b}")


multiply of two matrix
Two Matrix multiplied : 
[[  4  12  16]
 [180  36  49]]


Addition of two matrix
Two Matrix Added : 
[[ 4  7  8]
 [49 12 14]]


Subtraction of two matrix
Two Matrix Subtracted : 
[[ 0 -1  0]
 [41  0  0]]


Division of two matrix
Two Matrix Divided : 
[[ 1.    0.75  1.  ]
 [11.25  1.    1.  ]]


In [7]:
a=np.ones((4,9))
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]


# Range differnce

In [8]:
a=np.arange(1,10,2)
print(a)
a=np.arange(10,1,-2)
print(a)

[1 3 5 7 9]
[10  8  6  4  2]


# Empty

In [9]:
a=np.empty((2,4))
print(a)

[[5.11798224e-307 3.44897992e-307 1.69118108e-306 9.34609790e-307]
 [6.23037657e-307 9.34596889e-307 8.90060780e-307 3.49699467e-317]]


# cONDITION

In [10]:
A=np.ones((2,2))*5
print(A)
print(A>0)
A[A>0]
  

[[5. 5.]
 [5. 5.]]
[[ True  True]
 [ True  True]]


array([5., 5., 5., 5.])

In [11]:
A=np.ones((9,4))*1
b=np.ones((9,4))*0
c=np.ones((9,4))*1
d=np.ones((9,4))*0
e=np.ones((9,4))*1
print(A[A>0])
print(b[A>0])
print(c[A>0])
print(d[A>0])
print(e[A>0])


[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [12]:
NAMES=np.array(['ali','sadiq','kashif','khaid'])
FEES=np.array(['Submitted','Not-Submitted','Submitted',"Submitted"])
for i in NAMES[FEES=="Submitted"] :
    print("-",i)


- ali
- kashif
- khaid


In [13]:
NAMES[0:3]
NAMES[1:-2]

array(['sadiq'], dtype='<U6')

In [14]:
A=np.zeros((10,10))
A[0::2]=1
print(A)


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [15]:
B=np.ones((10,10),dtype=int16)
B[1::2]=0
B

NameError: name 'int16' is not defined

In [16]:
import numpy as np
ONES=np.ones((2,5))
print(ONES)

print("\n")

ONES=np.zeros((2,5))
print(ONES)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


# Random number genrated

In [37]:
random_num=np.random.randn(2,4)
print(random_num*2)

print("\n")
random_num=np.random.randn(2)
print(random_num*5)
print(random_num.dtype)
print(random_num.shape)


[[-3.28462243  0.34211389  3.07616698 -3.4156517 ]
 [ 2.54400647  0.24362479  0.84370113  1.54384882]]


[  6.30483166 -10.90487555]
float64
(2,)


# Created ndarray

# 1D array

In [64]:
data1=[1,2,4]
arr1=np.array(data1)
print(arr1)



print("\n")
names_data=['sadiq shah','Ali','kasim']
ages_data=[12,21,34]
sec_data=['B','A','C']
array1=np.array(names_data)
array2=np.array(ages_data)
array3=np.array(sec_data)
print(array1)
print(array2)
print(array3)
type(array1)
print("n-dimension",array1.ndim)







[1 2 4]


['sadiq shah' 'Ali' 'kasim']
[12 21 34]
['B' 'A' 'C']
n-dimension 1


# 2D array

In [70]:
_2D_array=[[1,2,3,4],[1 ,4,56]]
arr2D=np.array(_2D_array)
print(arr2D)
type(arr2D)

[list([1, 2, 3, 4]) list([1, 4, 56])]


numpy.ndarray

# Zeros

In [74]:
Zeros=np.zeros((2,2))
print(Zeros)
type(Zeros)

[[0. 0.]
 [0. 0.]]


numpy.ndarray

In [77]:
Zeros=np.zeros((4,4))
print(Zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [86]:
Ones=np.ones((10,10))
print(Ones)


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


TypeError: astype() missing required argument 'dtype' (pos 1)

# Convert Data type

In [95]:
print("1st Method")
print("Convert integer into float")
arr1=np.array([1,2,4],dtype="float32")
arr2=np.array([1,2,4],dtype=np.float32)
print(arr1)
print(arr2)
print("\n")



print("Convert float into integer")
arr1=np.array([1,2,4],dtype="int32")
arr2=np.array([1,2,4],dtype=np.int32)
print(arr1)
print(arr2)

1st Method
Convert integer into float
[1. 2. 4.]
[1. 2. 4.]


Convert float into integer
[1 2 4]
[1 2 4]


In [108]:
print("2nd method")
arr1=np.array([1,2,3,4,5])
arr2= np.array([3,4,5,6,6])
a=(arr1.astype(np.float32))
print(a)

b=arr2.astype(np.float64)
print(b)



arr2.astype(np.float64)
print(arr2)


2nd method
[1. 2. 3. 4. 5.]
[3. 4. 5. 6. 6.]
[3 4 5 6 6]


In [130]:
a=np.array([3.5,676.6,66.6])
a.astype(np.int32)
a=np.array([3.5,676.6,66.6],dtype="int32")
print(a)



# a.astype(np.String_)
numeric_strings = np.array(['1.25', '-9.6', '42'])
numeric_strings.astype(float)


[  3 676  66]


array([ 1.25, -9.6 , 42.  ])

array vs python: array doesnot contains same data but numpy contains same data

# Arithematic ndarray

In [150]:
# Addition
arr1=np.array([[1,3,4,5],[1,3,4,5]])
arr2=np.array([[1,5,7,8],[2,5,7,5]])
print(arr1)
print("     +")
print(arr2)
print()
arr=arr1+arr2
print(arr)

[[1 3 4 5]
 [1 3 4 5]]
     +
[[1 5 7 8]
 [2 5 7 5]]

[[ 2  8 11 13]
 [ 3  8 11 10]]


In [151]:
#Subtraction
arr1=np.array([[1,3,4,5],[1,3,4,5]])
arr2=np.array([[1,5,7,8],[2,5,7,5]])
print(arr1)
print("     -")
print(arr2)
print()
arr=arr1-arr2
print(arr)

[[1 3 4 5]
 [1 3 4 5]]
     -
[[1 5 7 8]
 [2 5 7 5]]

[[ 0 -2 -3 -3]
 [-1 -2 -3  0]]


In [152]:
#mulptiply
arr1=np.array([[1,3,4,5],[1,3,4,5]])
arr2=np.array([[1,5,7,8],[2,5,7,5]])
print(arr1)
print("     *")
print(arr2)
print()
arr=arr1*arr2
print(arr)

[[1 3 4 5]
 [1 3 4 5]]
     *
[[1 5 7 8]
 [2 5 7 5]]

[[ 1 15 28 40]
 [ 2 15 28 25]]


In [26]:
#mulptiply
arr1=np.array([[1,3,4,5],[1,3,4,5]])
arr2=np.array([[1,5,7,8],[2,5,7,5]])
print(arr1)
print("     /")
print(arr2)
print()
arr=arr1/arr2
print(arr)

[[1 3 4 5]
 [1 3 4 5]]
     /
[[1 5 7 8]
 [2 5 7 5]]

[[1.         0.6        0.57142857 0.625     ]
 [0.5        0.6        0.57142857 1.        ]]


# Condition

In [35]:
a=np.array([2.3,3.4,44.3])
a.astype(np.int32)

array([ 2,  3, 44])