# Basic Indexing and Slicing


# 1D Indexing and Slicing


In [2]:
import numpy as np

In [28]:
_1D_array=np.array([1,25,6,7])
print(_1D_array)
_1D_array_slice=_1D_array[3]
print(f"Slice element: {_1D_array_slice}\n")


print("Change the value of array")
_1D_array[0:2]=12
print(_1D_array)

print()
_1D_array[:]=12
print(_1D_array)


[ 1 25  6  7]
Slice element: 7

Change the value of array
[12 12  6  7]

[12 12 12 12]


In [61]:
_2D_array=np.array([[4,56,7,8] , [6,7,8,8]])
print(_2D_array)



print(_2D_array[0,0:1]) #rows
print(_2D_array[:,0:])   # coloumns




[[ 4 56  7  8]
 [ 6  7  8  8]]
[4]
[[ 4 56  7  8]
 [ 6  7  8  8]]


In [98]:
_3D_array=np.array([[[1,2,4,5]  ,  [1,2,4,5]] , [[13,25,46,53]  ,  [11,22,46,57]]  , [[71,28,48,55]  ,  [19,20,48,58]],[[71,28,48,55]  ,  [122,206,468,548]],[[731,238,448,545]  ,  [119,320,478,598]]])
print(_3D_array)
print(_3D_array[1,:,0])
print(_3D_array[1,:,3])
print(_3D_array[1,0])
print(_3D_array[ 2, : , 2])
print(_3D_array[1:2,0:,2:] )


print(_3D_array[4,:,2])


[[[  1   2   4   5]
  [  1   2   4   5]]

 [[ 13  25  46  53]
  [ 11  22  46  57]]

 [[ 71  28  48  55]
  [ 19  20  48  58]]

 [[ 71  28  48  55]
  [122 206 468 548]]

 [[731 238 448 545]
  [119 320 478 598]]]
[13 11]
[53 57]
[13 25 46 53]
[48 48]
[[[46 53]
  [46 57]]]
[448 478]


In [13]:
_2d_array=np.arange(1,101).reshape(10,10)
print(_2d_array)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [23]:
print(_2d_array[0,0])# 0 row and 0 coloumns
print("Dimension : " , _2d_array[0,0].ndim)   # scalar(no dimension)



1
Dimension :  0


In [26]:
print(_2d_array[0])

print("Dimension : " ,_2d_array[0:3].ndim)  #vector (2d dimnesion)

[ 1  2  3  4  5  6  7  8  9 10]
Dimension :  2


In [27]:
# All rows but particular coloums
coloums=_2d_array[: , 0]
print(coloums)

[ 1 11 21 31 41 51 61 71 81 91]


In [30]:
coloums=_2d_array[ : , 5]
print(coloums)

[ 6 16 26 36 46 56 66 76 86 96]


In [54]:
coloumns=_2d_array[0:2,8:10]
print(coloumns)

[[ 9 10]
 [19 20]]


In [40]:
_2d_array

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [60]:
print(_2d_array[0:,0:1] ) # by 2d one coloum
print(_2d_array[0:,0:1].ndim)

[[ 1]
 [11]
 [21]
 [31]
 [41]
 [51]
 [61]
 [71]
 [81]
 [91]]
2


In [61]:
print(_2d_array[0:,0])  # by 1d one coloum
print(_2d_array[0:,0:1].ndim)

[ 1 11 21 31 41 51 61 71 81 91]
2


In [71]:
 _2d_array[0:4 , 0:4 ]

array([[ 1,  2,  3,  4],
       [11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34]])

In [72]:
 _2d_array[1:4 , 1:4 ]

array([[12, 13, 14],
       [22, 23, 24],
       [32, 33, 34]])

In [94]:
 _2d_array[9: , 8:10]

array([[ 99, 100]])

In [105]:
 _2d_array[0 , 6:]

array([ 7,  8,  9, 10])

In [107]:
 _2d_array[0: , 1:3]  # all rows and 2 coloumns

array([[ 2,  3],
       [12, 13],
       [22, 23],
       [32, 33],
       [42, 43],
       [52, 53],
       [62, 63],
       [72, 73],
       [82, 83],
       [92, 93]])

In [111]:
 print(_2d_array[ : ])#find complete matrix


[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [112]:
 print(_2d_array[::])

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [113]:
print( print(_2d_array[: , :]))

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]
None


# How many size consumed by array

In [118]:
print(_2d_array.itemsize)
print(_2d_array.dtype)


4
int32


In [123]:
# int32 = 32bit

# 32bit means 4byte...
# 1byte = 8bit

# 32/8  each array contains the 4 bit..

