In [1]:
import numpy as np
import random

# Randn
its give positive as well as negative values

In [7]:
randn=np.random.randn(3,3)
print(randn)

[[-0.54876224  0.32978292 -0.59768687]
 [-2.87151683  0.46380709  0.19081372]
 [ 2.21959483  0.93513546 -0.52896748]]


# Rand
all will be positive

In [8]:
randn=np.random.rand(3,3)
print(randn)

[[0.08312271 0.72548525 0.51976933]
 [0.84700211 0.29402109 0.06163807]
 [0.10971538 0.89487588 0.56583218]]


# Randint
its give value low to approx

In [14]:
randint=np.random.randint(10, size=10)
print(randint)

[6 4 9 3 7 5 2 7 3 6]


In [20]:
randint=np.random.randint(100, size=100)
print(randint)

[68 18 92 61 73 46 49 70 11 43 18  8 24 80 55 22 95 78 90  5 10 59 37 39
 82 32  1 99 28 16 65 61 65 19 76 51 24 50 24 19  3 70 22 42 15 49 54 27
 66 41 63  3 59 53 84 54 68 13 69 26 74 37 22 72 58 91 84  6 84 65 19 41
 46 61 44 83 23 17 79 26 49 57  5 66 27  7  2 47 28 77 29 23 47  4 91 37
 47 25 97 84]


In [ ]:
seed=np.random

In [ ]:
https://docs.scipy.org/doc/numpy-1.14.1/reference/routines.random.html
#     its randome sampling